//list of detailed subpages

var detailedSubpages = [
    {pageName: 'Sea Shrimp', webLink: 'sea-shrimp.html', shortDescription: 'A small shrimp, complete with two front claws and its distinguishable flexible tail.', detailedDescription: 'This is one of the more recent models that I came up with. Featuring two front claws and a flexible tail, this shrimp is intricate yet easy to fold. This is a model that was sort of inspired by the Attacker Fish model.', difficulty: 5.5, time: '10-14 min', image: 'https://pitchk.github.io/h/shrimp.jpg', instructions: 'https://pitchk.github.io/sea-shrimp/shrimp.svg', download: 'https://pitchk.github.io/sea-shrimp/shrimp.pdf', images: [{url: 'https://pitchk.github.io/sea-shrimp/shrimptop.jpg', caption: 'Top View.'}, {url: 'https://pitchk.github.io/sea-shrimp/twoshrimp.jpg', caption: 'Two shrimp, side by side.'}]},

    {pageName: 'Attacker Fish', webLink: 'attacker-fish.html', shortDescription: '(No description provided)', detailedDescription: 'This model inspired the Sea Shrimp. If this fish were to appear in real life, it would feature two fins in the back to propel it through the water quickly, while having two claws in the front to capture anything that swims past it.', difficulty: 6.5, time: '12-20 min', image: 'https://pitchk.github.io/attacker-fish/attackerfish.jpg', instructions: 'https://pitchk.github.io/attacker-fish/attackerfish.svg', download: 'https://pitchk.github.io/attacker-fish/attackerfish.pdf', images: [{url: 'https://pitchk.github.io/sea-shrimp/shrimptop.jpg', caption: 'Top View.'}, {url: 'https://pitchk.github.io/sea-shrimp/twoshrimp.jpg', caption: 'Two shrimp, side by side.'}]},

    {pageName: 'A simple robot', webLink: 'simple-robot.html', shortDescription: 'A robot that is ready to fight anything that comes in its way. Looks great on your desk!', detailedDescription: 'As of December 2021, this model is the most recent model I made up. An interesting fact is that I created it by accident while trying to come up with a new futuristic vehicle. This robot looks great on your desk, folded in a bright color!', difficulty: 7.5, time: '10-15 min', image: 'https://pitchk.github.io/h/robot.jpg', instructions: 'https://pitchk.github.io/simple-robot/robot.svg', images: [{url: 'https://pitchk.github.io/sea-shrimp/shrimptop.jpg', caption: 'Top View.'}, {url: 'https://pitchk.github.io/sea-shrimp/twoshrimp.jpg', caption: 'Two shrimp, side by side.'}]}, 
    
    {pageName: 'A simple plant (ver. 1)', webLink: 'plant1.html', shortDescription: '(No description provided)', detailedDescription: 'One of my easiest models! This plant stands on four \'legs\' and has a sharp point that is elevated in the center. It has four leaves (or petals, whichever way you may want to view it as!) This model inspired both Version 2 and the tall plant.', difficulty: 3, time: '7-12 min', image: 'https://pitchk.github.io/plant-1/plant1.jpg', instructions: 'https://pitchk.github.io/plant-1/flower1.svg', images: [{url: 'https://pitchk.github.io/sea-shrimp/shrimptop.jpg', caption: 'Top View.'}, {url: 'https://pitchk.github.io/sea-shrimp/twoshrimp.jpg', caption: 'Two shrimp, side by side.'}]},

    {pageName: 'A simple plant (ver. 2)', webLink: 'plant2.html', shortDescription: '(No description provided)', detailedDescription: 'This looks exactly the same as "A Simple Plant (Ver. 1)" but it is a fourth of its size. Although this model is slighly harder and takes longer to fold, it is much more sturdy and has multiple layers under its leaves (or petals).', difficulty: 6, time: '12-20 min', image: 'https://pitchk.github.io/plant-2/plant2real.jpg', instructions: 'https://pitchk.github.io/plant-2/flower2.svg', images: [{url: 'https://pitchk.github.io/plant-2/plant22.jpg', caption: 'Top View.'}, {url: 'https://pitchk.github.io/plant-2/plant21.jpg', caption: 'This model can be compactly folded up!'}]},

    {pageName: 'Tank with long cannon', webLink: 'tank-w-long-cannon.html', shortDescription: 'Folding this on a 6in x 6in square paper would allow a Lego minifigure to fit perfectly behind the cannon!', detailedDescription: 'This model is simple yet fun to fold at the same time - its main feature is the long cannon that extends more than the body\'s length. Unlike my other tanks that looks like it can shoot only straight ahead, this looks as if it could lob a cannonball in a parabolic curve.', difficulty: 5, time: '8-13 min', image: 'https://pitchk.github.io/h/Long_tank.jpg', instructions: 'https://pitchk.github.io/tank-with-long-cannon/tank_w_long_cannon.svg', images: [{url: 'https://pitchk.github.io/plant-2/plant22.jpg', caption: 'Top View.'}, {url: 'https://pitchk.github.io/plant-2/plant21.jpg', caption: 'This model can be compactly folded up!'}]},
];


