//list of detailed subpages

var detailedSubpages = [
    {pageName: 'Sea Shrimp', webLink: 'sea-shrimp.html', shortDescription: 'A small shrimp, complete with two front claws and its distinguishable flexible tail.', detailedDescription: 'This is one of the more recent models that I came up with. Featuring two front claws and a flexible tail, this shrimp is intricate yet easy to fold. This is a model that was sort of inspired by the Attacker Fish model.', difficulty: 5.5, time: '10-14 min', image: 'https://pitchk.github.io/h/shrimp.jpg', instructions: 'https://pitchk.github.io/sea-shrimp/shrimp.svg', download: 'https://pitchk.github.io/sea-shrimp/shrimp.pdf', images: [{url: 'https://pitchk.github.io/sea-shrimp/shrimptop.jpg', caption: 'Top View.'}, {url: 'https://pitchk.github.io/sea-shrimp/twoshrimp.jpg', caption: 'Two shrimp, side by side.'}]},

    {pageName: 'Attacker Fish', webLink: 'attacker-fish.html', shortDescription: '(No description provided)', detailedDescription: 'This model inspired the Sea Shrimp. If this fish were to appear in real life, it would feature two fins in the back to propel it through the water quickly, while having two claws in the front to capture anything that swims past it.', difficulty: 6.5, time: '12-20 min', image: 'https://pitchk.github.io/attacker-fish/attackerfish.jpg', instructions: 'https://pitchk.github.io/attacker-fish/attackerfish.svg', download: 'https://pitchk.github.io/attacker-fish/attackerfish.pdf', images: []},

    {pageName: 'A simple robot', webLink: 'simple-robot.html', shortDescription: 'A robot that is ready to fight anything that comes in its way. Looks great on your desk!', detailedDescription: 'As of December 2021, this model is the most recent model I made up. An interesting fact is that I created it by accident while trying to come up with a new futuristic vehicle. This robot looks great on your desk, folded in a bright color!', difficulty: 7.5, time: '10-15 min', image: 'https://pitchk.github.io/h/robot.jpg', instructions: 'https://pitchk.github.io/simple-robot/robot.svg', images: []}, 
    
    {pageName: 'A simple plant (ver. 1)', webLink: 'plant1.html', shortDescription: '(No description provided)', detailedDescription: 'One of my easiest models! This plant stands on four \'legs\' and has a sharp point that is elevated in the center. It has four leaves (or petals, whichever way you may want to view it as!) This model inspired both Version 2 and the tall plant.', difficulty: 3, time: '7-12 min', image: 'https://pitchk.github.io/plant-1/plant1.jpg', instructions: 'https://pitchk.github.io/plant-1/flower1.svg', images: []},

    {pageName: 'A simple plant (ver. 2)', webLink: 'plant2.html', shortDescription: '(No description provided)', detailedDescription: 'This looks exactly the same as "A Simple Plant (Ver. 1)" but it is a fourth of its size. Although this model is slighly harder and takes longer to fold, it is much more sturdy and has multiple layers under its leaves (or petals).', difficulty: 6, time: '12-20 min', image: 'https://pitchk.github.io/plant-2/plant2real.jpg', instructions: 'https://pitchk.github.io/plant-2/flower2.svg', images: [{url: 'https://pitchk.github.io/plant-2/plant22.jpg', caption: 'Top View.'}, {url: 'https://pitchk.github.io/plant-2/plant21.jpg', caption: 'This model can be compactly folded up!'}]},

    {pageName: 'Tank with long cannon', webLink: 'tank-w-long-cannon.html', shortDescription: 'Folding this on a 6in x 6in square paper would allow a Lego minifigure to fit perfectly behind the cannon!', detailedDescription: 'This model is simple yet fun to fold at the same time - its main feature is the long cannon that extends more than the body\'s length. Unlike my other tanks that looks like it can shoot only straight ahead, this looks as if it could lob a cannonball in a parabolic curve.', difficulty: 5, time: '8-13 min', image: 'https://pitchk.github.io/h/Long_tank.jpg', instructions: 'https://pitchk.github.io/tank-with-long-cannon/tank_w_long_cannon.svg', images: []},

    {pageName: 'Futuristic Boat', webLink: 'futuristicboat.html', shortDescription: 'A twist on the LandHover\'21. Now featuring two large back jets! Looks even faster!', detailedDescription: 'This was inspired by the LandHover\'21. However, instead of speeding on land, this is designed to skim across water instead. This looks very fast and very light, and could possibly exist in the future as a recreational boat.', difficulty: 5.5, time: '13-19 min', image: 'https://pitchk.github.io/futuristic-boat/fv9.jpg', instructions: 'https://pitchk.github.io/futuristic-boat/fv9.svg', images: [{url: 'https://pitchk.github.io/futuristic-boat/fv91.jpg', caption: 'Top View.'}, {url: 'https://pitchk.github.io/futuristic-boat/fv92.jpg', caption: '"Diagonal" view.'}]},

    {pageName: 'Land Hover\'21 ', webLink: 'land-hover-21.html', shortDescription: 'This model was sort of inspired by the landspeeder in Star Wars, as you can see. Doesn\'t it look fast?', detailedDescription: 'This model is the 6th original model that I came up with. It features an open cockpit with an engine above it, and two tail jets in the back to propel the vehicle forward. If this vehicle would exist in the future, it could hover above ground while reaching a ridiculous speed! This model is a twist of my first original model.', difficulty: 7, time: '12-18 min', image: 'https://pitchk.github.io/h/speedr.jpg', instructions: 'https://pitchk.github.io/land-hover-21/fv6.svg', images: [{url: 'https://pitchk.github.io/land-hover-21/fv61.jpg', caption: 'Side View.'}, {url: 'https://pitchk.github.io/land-hover-21/fv64.jpg', caption: 'Crease lines for this model.'}]},

    {pageName: 'Air Point\'21 ', webLink: 'air-point-21.html', shortDescription: 'This model\'s distinguishable characteristic is that sharp point. Fold with black origami for the best contrast!', detailedDescription: 'This model is the 4th original model that I came up with. Featuring a distinguishable cockpit and a sharp point in the front, the AirPoint \'21 truly deserves its name. If this model was made in real life, its length would be no more than 20 feet, with a cockpit that can only seat two people. This looks like a vehicle that would be flown around just for fun in the future!', difficulty: 4.5, time: '12-15 min', image: 'https://pitchk.github.io/h/point.jpg', instructions: 'https://pitchk.github.io/air-point-21/fv4.svg', images: []}
];


